# Generated by Django 2.2.24 on 2021-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210713_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
